# Generated by Django 5.0.5 on 2024-05-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UserAuth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailverification",
            name="Email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="phoneverification",
            name="PhoneNumber",
            field=models.CharField(max_length=15),
        ),
    ]
